services:
  backend:
    build: ./backend
    expose:
      - "${INTERNAL_APP_PORT:-8000}"
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "${EXTERNAL_PORT:-80}:80"
    depends_on:
      - backend
    restart: always
